// 词库数据
const wordLibraries = {
    // 大学英语四级词汇
    cet4: [
        { word: "abandon", phonetic: "/əˈbændən/", meaning: "vt. 放弃，遗弃 n. 放任，放纵" },
        { word: "ability", phonetic: "/əˈbɪləti/", meaning: "n. 能力，能耐，才能" },
        { word: "able", phonetic: "/ˈeɪbl/", meaning: "a. 有能力的，出色的" },
        { word: "abnormal", phonetic: "/æbˈnɔːml/", meaning: "a. 不正常的，变态的" },
        { word: "aboard", phonetic: "/əˈbɔːd/", meaning: "ad. 在船(车)上，上船" },
        { word: "about", phonetic: "/əˈbaʊt/", meaning: "prep. 关于，在…周围" },
        { word: "above", phonetic: "/əˈbʌv/", meaning: "prep. 在…上面，高于" },
        { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "ad. (在)国外，到处" },
        { word: "absence", phonetic: "/ˈæbsəns/", meaning: "n. 缺席，不在场，缺乏" },
        { word: "absent", phonetic: "/ˈæbsənt/", meaning: "a. 不在场的，缺乏的" },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "a. 绝对的，完全的" },
        { word: "absorb", phonetic: "/əbˈsɔːb/", meaning: "vt. 吸收，使专心" },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "a. 抽象的 n. 摘要" },
        { word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "a. 丰富的，充分的" },
        { word: "abuse", phonetic: "/əˈbjuːs/", meaning: "vt. 滥用，虐待 n. 滥用" },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "a. 学术的，教学的" },
        { word: "academy", phonetic: "/əˈkædəmi/", meaning: "n. 学院，研究院" },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "vt. 加速，促进" },
        { word: "accent", phonetic: "/ˈæksent/", meaning: "n. 口音，腔调，重音" },
        { word: "accept", phonetic: "/əkˈsept/", meaning: "vt. 接受，认可" },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 接近，通道，入口" },
        { word: "accident", phonetic: "/ˈæksɪdənt/", meaning: "n. 意外的，事故" },
        { word: "accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "n. 住处，膳宿" },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "vt. 陪伴，陪同，伴随" },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "vt. 达到(目的)，完成" },
        { word: "according", phonetic: "/əˈkɔːdɪŋ/", meaning: "ad. 依照" },
        { word: "account", phonetic: "/əˈkaʊnt/", meaning: "n. 记述，解释，账目" },
        { word: "accumulate", phonetic: "/əˈkjuːmjuleɪt/", meaning: "vt. 积累 vi. 堆积" },
        { word: "accuracy", phonetic: "/ˈækjərəsi/", meaning: "n. 准确(性)，精确" },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "a. 准确的，正确无误的" },
        { word: "accuse", phonetic: "/əˈkjuːz/", meaning: "vt. 指责，归咎于" },
        { word: "accustomed", phonetic: "/əˈkʌstəmd/", meaning: "a. 惯常的，习惯的" },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "vt. 完成，达到，获得" },
        { word: "achievement", phonetic: "/əˈtʃiːvmənt/", meaning: "n. 成就，完成，达到" },
        { word: "acid", phonetic: "/ˈæsɪd/", meaning: "a. 酸的，酸性的" },
        { word: "acquaintance", phonetic: "/əˈkweɪntəns/", meaning: "n. 认识，了解，熟人" },
        { word: "acquire", phonetic: "/əˈkwaɪə(r)/", meaning: "vt. 取得，获得，学到" },
        { word: "acquisition", phonetic: "/ˌækwɪˈzɪʃn/", meaning: "n. 取得，获得物" },
        { word: "across", phonetic: "/əˈkrɒs/", meaning: "prep. 横过，在…对面" },
        { word: "act", phonetic: "/ækt/", meaning: "v. 行动，表演 n. 行为" },
        { word: "action", phonetic: "/ˈækʃn/", meaning: "n. 行动，作用，功能" },
        { word: "active", phonetic: "/ˈæktɪv/", meaning: "a. 活跃的，积极的" },
        { word: "activity", phonetic: "/ækˈtɪvəti/", meaning: "n. 活动，活力，行动" },
        { word: "actor", phonetic: "/ˈæktə(r)/", meaning: "n. 男演员" },
        { word: "actress", phonetic: "/ˈæktrəs/", meaning: "n. 女演员" },
        { word: "actual", phonetic: "/ˈæktʃuəl/", meaning: "a. 实际的，现行的" },
        { word: "actually", phonetic: "/ˈæktʃuəli/", meaning: "ad. 实际上，事实上" },
        { word: "acute", phonetic: "/əˈkjuːt/", meaning: "a. 严重的，急性的" },
        { word: "adapt", phonetic: "/əˈdæpt/", meaning: "vt. 使适应，改编" },
        { word: "add", phonetic: "/æd/", meaning: "vt. 添加，增加，加" },
        { word: "addicted", phonetic: "/əˈdɪktɪd/", meaning: "a. 上瘾的，入迷的" },
        { word: "addition", phonetic: "/əˈdɪʃn/", meaning: "n. 加，加法，附加物" },
        { word: "additional", phonetic: "/əˈdɪʃənl/", meaning: "a. 附加的，追加的" },
        { word: "address", phonetic: "/əˈdres/", meaning: "n. 地址，演说 vt. 演说" },
        { word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "a. 足够的，适当的" },
        { word: "adjust", phonetic: "/əˈdʒʌst/", meaning: "vt. 调整，调节，校正" },
        { word: "administer", phonetic: "/ədˈmɪnɪstə(r)/", meaning: "vt. 管理，执行，治理" },
        { word: "administration", phonetic: "/ədˌmɪnɪˈstreɪʃn/", meaning: "n. 管理，行政，政府" },
        { word: "admire", phonetic: "/ədˈmaɪə(r)/", meaning: "vt. 钦佩，赞美，羡慕" },
        { word: "admission", phonetic: "/ədˈmɪʃn/", meaning: "n. 允许进入，承认" },
        { word: "admit", phonetic: "/ədˈmɪt/", meaning: "vt. 承认，准许…进入" },
        { word: "adopt", phonetic: "/əˈdɒpt/", meaning: "vt. 收养，采用，采取" },
        { word: "adult", phonetic: "/ˈædʌlt/", meaning: "n. 成年人 a. 成年的" },
        { word: "advance", phonetic: "/ədˈvɑːns/", meaning: "v. 前进，提高 n. 前进" },
        { word: "advanced", phonetic: "/ədˈvɑːnst/", meaning: "a. 先进的，高级的" },
        { word: "advantage", phonetic: "/ədˈvɑːntɪdʒ/", meaning: "n. 优点，优势，好处" },
        { word: "adventure", phonetic: "/ədˈventʃə(r)/", meaning: "n. 冒险，冒险活动" },
        { word: "adverb", phonetic: "/ˈædvɜːb/", meaning: "n. 副词" },
        { word: "advertise", phonetic: "/ˈædvətaɪz/", meaning: "vt. 为…做广告" },
        { word: "advertisement", phonetic: "/ədˈvɜːtɪsmənt/", meaning: "n. 广告，公告，启事" },
        { word: "advice", phonetic: "/ədˈvaɪs/", meaning: "n. 劝告，忠告，意见" },
        { word: "advise", phonetic: "/ədˈvaɪz/", meaning: "vt. 劝告，建议，通知" },
        { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "vt. 提倡，主张 n. 提倡者" },
        { word: "aeroplane", phonetic: "/ˈeərəpleɪn/", meaning: "n. 飞机" },
        { word: "affair", phonetic: "/əˈfeə(r)/", meaning: "n. 事情，事件，事务" },
        { word: "affect", phonetic: "/əˈfekt/", meaning: "vt. 影响，感动，假装" },
        { word: "affection", phonetic: "/əˈfekʃn/", meaning: "n. 感情，慈爱，爱" },
        { word: "afford", phonetic: "/əˈfɔːd/", meaning: "vt. 担负得起，提供" },
        { word: "afraid", phonetic: "/əˈfreɪd/", meaning: "a. 害怕的，担心的" },
        { word: "Africa", phonetic: "/ˈæfrɪkə/", meaning: "n. 非洲" },
        { word: "African", phonetic: "/ˈæfrɪkən/", meaning: "a. 非洲的 n. 非洲人" },
        { word: "after", phonetic: "/ˈɑːftə(r)/", meaning: "prep. 在…以后，次于" },
        { word: "afternoon", phonetic: "/ˌɑːftəˈnuːn/", meaning: "n. 下午，午后" },
        { word: "afterward", phonetic: "/ˈɑːftəwəd/", meaning: "ad. 后来，以后" },
        { word: "again", phonetic: "/əˈɡen/", meaning: "ad. 又，再，再次" },
        { word: "against", phonetic: "/əˈɡenst/", meaning: "prep. 反对，违反，靠着" },
        { word: "age", phonetic: "/eɪdʒ/", meaning: "n. 年龄，时代，阶段" },
        { word: "agency", phonetic: "/ˈeɪdʒənsi/", meaning: "n. 经办，代理，代理处" },
        { word: "agent", phonetic: "/ˈeɪdʒənt/", meaning: "n. 代理人，代理商" },
        { word: "ago", phonetic: "/əˈɡəʊ/", meaning: "ad. 以前，以往" },
        { word: "agree", phonetic: "/əˈɡriː/", meaning: "v. 同意，赞成，一致" },
        { word: "agreement", phonetic: "/əˈɡriːmənt/", meaning: "n. 协议，同意，一致" },
        { word: "agriculture", phonetic: "/ˈæɡrɪkʌltʃə(r)/", meaning: "n. 农业，农艺，农学" },
        { word: "ahead", phonetic: "/əˈhed/", meaning: "ad. 在前，向前，提前" },
        { word: "aid", phonetic: "/eɪd/", meaning: "n. 援助，救护，助手" },
        { word: "aim", phonetic: "/eɪm/", meaning: "v. 瞄准，旨在 n. 目标" },
        { word: "air", phonetic: "/eə(r)/", meaning: "n. 空气，大气，态度" },
        { word: "aircraft", phonetic: "/ˈeəkrɑːft/", meaning: "n. 飞机，飞行器" },
        { word: "airline", phonetic: "/ˈeəlaɪn/", meaning: "n. 航空公司，航线" },
        { word: "airport", phonetic: "/ˈeəpɔːt/", meaning: "n. 机场，航空站" },
        { word: "aisle", phonetic: "/aɪl/", meaning: "n. 过道，通道" },
        { word: "alarm", phonetic: "/əˈlɑːm/", meaning: "n. 警报，惊慌，警报器" },
        { word: "album", phonetic: "/ˈælbəm/", meaning: "n. 集邮本，照相簿，唱片" },
        { word: "alcohol", phonetic: "/ˈælkəhɒl/", meaning: "n. 酒精，乙醇" },
        { word: "alert", phonetic: "/əˈlɜːt/", meaning: "a. 警惕的，活跃的" },
        { word: "alien", phonetic: "/ˈeɪliən/", meaning: "a. 外国的，陌生的" },
        { word: "alike", phonetic: "/əˈlaɪk/", meaning: "a. 相同的，相像的" },
        { word: "alive", phonetic: "/əˈlaɪv/", meaning: "a. 活着的，活跃的" },
        { word: "all", phonetic: "/ɔːl/", meaning: "a. 全部的，所有的" },
        { word: "allow", phonetic: "/əˈlaʊ/", meaning: "vt. 允许，准许，任" },
        { word: "allowance", phonetic: "/əˈlaʊəns/", meaning: "n. 津贴，补助费" },
        { word: "alloy", phonetic: "/ˈælɔɪ/", meaning: "n. 合金 vt. 使成合金" },
        { word: "alone", phonetic: "/əˈləʊn/", meaning: "a. 单独的，孤独的" },
        { word: "along", phonetic: "/əˈlɒŋ/", meaning: "prep. 沿着，顺着" },
        { word: "aloud", phonetic: "/əˈlaʊd/", meaning: "ad. 出声地，大声地" },
        { word: "alphabet", phonetic: "/ˈælfəbet/", meaning: "n. 字母表，字母系统" },
        { word: "already", phonetic: "/ɔːlˈredi/", meaning: "ad. 早已，已经" },
        { word: "also", phonetic: "/ˈɔːlsəʊ/", meaning: "ad. 也，而且，同样" },
        { word: "alternative", phonetic: "/ɔːlˈtɜːnətɪv/", meaning: "a. 两者择一的 n. 选择" },
        { word: "although", phonetic: "/ɔːlˈðəʊ/", meaning: "conj. 尽管，虽然" },
        { word: "altitude", phonetic: "/ˈæltɪtjuːd/", meaning: "n. 高度，海拔，高处" },
        { word: "altogether", phonetic: "/ˌɔːltəˈɡeðə(r)/", meaning: "ad. 完全，总而言之" },
        { word: "aluminium", phonetic: "/ˌæljəˈmɪniəm/", meaning: "n. 铝" },
        { word: "always", phonetic: "/ˈɔːlweɪz/", meaning: "ad. 总是，永远，始终" },
        { word: "a.m.", phonetic: "/ˌeɪ ˈem/", meaning: "上午，午前" },
        { word: "amateur", phonetic: "/ˈæmətə(r)/", meaning: "a. 业余的 n. 业余爱好者" },
        { word: "amaze", phonetic: "/əˈmeɪz/", meaning: "vt. 使惊奇，使惊愕" },
        { word: "ambassador", phonetic: "/æmˈbæsədə(r)/", meaning: "n. 大使，使节" },
        { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", meaning: "a. 模棱两可的，含糊的" },
        { word: "ambition", phonetic: "/æmˈbɪʃn/", meaning: "n. 雄心，抱负，野心" },
        { word: "ambitious", phonetic: "/æmˈbɪʃəs/", meaning: "a. 有雄心的，野心勃勃的" },
        { word: "ambulance", phonetic: "/ˈæmbjələns/", meaning: "n. 救护车，野战医院" },
        { word: "America", phonetic: "/əˈmerɪkə/", meaning: "n. 美洲，美国" },
        { word: "American", phonetic: "/əˈmerɪkən/", meaning: "a. 美洲的 n. 美洲人" },
        { word: "among", phonetic: "/əˈmʌŋ/", meaning: "prep. 在…之中，在…中间" },
        { word: "amount", phonetic: "/əˈmaʊnt/", meaning: "n. 数量，总额 vi. 合计" },
        { word: "ample", phonetic: "/ˈæmpl/", meaning: "a. 足够的，宽敞的" },
        { word: "amplify", phonetic: "/ˈæmplɪfaɪ/", meaning: "vt. 放大，增强，扩大" },
        { word: "amuse", phonetic: "/əˈmjuːz/", meaning: "vt. 逗…乐，给…娱乐" },
        { word: "analyse", phonetic: "/ˈænəlaɪz/", meaning: "vt. 分析，分解，解析" },
        { word: "analysis", phonetic: "/əˈnæləsɪs/", meaning: "n. 分析，分解，解析" },
        { word: "analytic", phonetic: "/ˌænəˈlɪtɪk/", meaning: "a. 分析的，解析的" },
        { word: "ancestor", phonetic: "/ˈænsestə(r)/", meaning: "n. 祖宗，祖先" },
        { word: "anchor", phonetic: "/ˈæŋkə(r)/", meaning: "n. 锚 vi. 抛锚，停泊" },
        { word: "ancient", phonetic: "/ˈeɪnʃənt/", meaning: "a. 古代的，古老的" },
        { word: "and", phonetic: "/ænd/", meaning: "conj. 和，与，而且" },
        { word: "anger", phonetic: "/ˈæŋɡə(r)/", meaning: "n. 怒，愤怒 vt. 使发怒" },
        { word: "angle", phonetic: "/ˈæŋɡl/", meaning: "n. 角，角度" },
        { word: "angry", phonetic: "/ˈæŋɡri/", meaning: "a. 愤怒的，生气的" },
        { word: "animal", phonetic: "/ˈænɪml/", meaning: "n. 动物，兽，牲畜" },
        { word: "ankle", phonetic: "/ˈæŋkl/", meaning: "n. 踝，踝节部" },
        { word: "anniversary", phonetic: "/ˌænɪˈvɜːsəri/", meaning: "n. 周年纪念(日)" },
        { word: "announce", phonetic: "/əˈnaʊns/", meaning: "vt. 宣布，宣告，发表" },
        { word: "annoy", phonetic: "/əˈnɔɪ/", meaning: "vt. 使恼怒，打搅" },
        { word: "annual", phonetic: "/ˈænjuəl/", meaning: "a. 每年的，一年生的" },
        { word: "anonymous", phonetic: "/əˈnɒnɪməs/", meaning: "a. 匿名的，无名的" },
        { word: "another", phonetic: "/əˈnʌðə(r)/", meaning: "a. 另一，再一，别的" },
        { word: "answer", phonetic: "/ˈɑːnsə(r)/", meaning: "n. 回答，答案 v. 回答" },
        { word: "ant", phonetic: "/ænt/", meaning: "n. 蚂蚁" },
        { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", meaning: "vt. 预料，预期，期望" },
        { word: "antique", phonetic: "/ænˈtiːk/", meaning: "a. 古代的 n. 古物" },
        { word: "anxiety", phonetic: "/æŋˈzaɪəti/", meaning: "n. 焦虑，忧虑，渴望" },
        { word: "anxious", phonetic: "/ˈæŋkʃəs/", meaning: "a. 忧虑的，渴望的" },
        { word: "any", phonetic: "/ˈeni/", meaning: "a. 什么，一些，任何的" },
        { word: "anybody", phonetic: "/ˈenibɒdi/", meaning: "pron. 任何人" },
        { word: "anyhow", phonetic: "/ˈenihaʊ/", meaning: "ad. 无论如何" },
        { word: "anyone", phonetic: "/ˈeniwʌn/", meaning: "pron. 任何人" },
        { word: "anything", phonetic: "/ˈeniθɪŋ/", meaning: "pron. 任何事物" },
        { word: "anyway", phonetic: "/ˈeniweɪ/", meaning: "ad. 无论如何" },
        { word: "anywhere", phonetic: "/ˈeniweə(r)/", meaning: "ad. 无论何处" },
        { word: "apart", phonetic: "/əˈpɑːt/", meaning: "ad. 相隔，分开，除去" },
        { word: "apartment", phonetic: "/əˈpɑːtmənt/", meaning: "n. 一套公寓房间" },
        { word: "apologize", phonetic: "/əˈpɒlədʒaɪz/", meaning: "vi. 道歉，谢罪，认错" },
        { word: "apology", phonetic: "/əˈpɒlədʒi/", meaning: "n. 道歉，认错，谢罪" },
        { word: "apparent", phonetic: "/əˈpærənt/", meaning: "a. 表面上的，明显的" },
        { word: "appeal", phonetic: "/əˈpiːl/", meaning: "vi. 呼吁，要求，上诉" },
        { word: "appear", phonetic: "/əˈpɪə(r)/", meaning: "vi. 出现，来到，似乎" },
        { word: "appearance", phonetic: "/əˈpɪərəns/", meaning: "n. 出现，来到，外观" },
        { word: "appendix", phonetic: "/əˈpendɪks/", meaning: "n. 附录，附属物" },
        { word: "appetite", phonetic: "/ˈæpɪtaɪt/", meaning: "n. 食欲，胃口，欲望" },
        { word: "applaud", phonetic: "/əˈplɔːd/", meaning: "vt. 喝彩，欢呼，称赞" },
        { word: "apple", phonetic: "/ˈæpl/", meaning: "n. 苹果，苹果树" },
        { word: "application", phonetic: "/ˌæplɪˈkeɪʃn/", meaning: "n. 请求，申请，施用" },
        { word: "apply", phonetic: "/əˈplaɪ/", meaning: "vt. 应用，实施，使用" },
        { word: "appoint", phonetic: "/əˈpɔɪnt/", meaning: "vt. 任命，约定，指定" },
        { word: "appointment", phonetic: "/əˈpɔɪntmənt/", meaning: "n. 任命，约定，约会" },
        { word: "appraisal", phonetic: "/əˈpreɪzl/", meaning: "n. 估计，评价，鉴定" },
        { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", meaning: "vt. 欣赏，领会，感谢" },
        { word: "approach", phonetic: "/əˈprəʊtʃ/", meaning: "v. 向…靠近 n. 靠近" },
        { word: "appropriate", phonetic: "/əˈprəʊpriət/", meaning: "a. 适当的，恰当的" },
        { word: "approve", phonetic: "/əˈpruːv/", meaning: "vt. 赞成，批准，通过" },
        { word: "approximate", phonetic: "/əˈprɒksɪmət/", meaning: "a. 近似的 vt. 近似" },
        { word: "April", phonetic: "/ˈeɪprəl/", meaning: "n. 四月" },
        { word: "Arab", phonetic: "/ˈærəb/", meaning: "a. 阿拉伯的 n. 阿拉伯人" },
        { word: "Arabic", phonetic: "/ˈærəbɪk/", meaning: "a. 阿拉伯的 n. 阿拉伯语" },
        { word: "arch", phonetic: "/ɑːtʃ/", meaning: "n. 拱门，弓形结构" },
        { word: "architect", phonetic: "/ˈɑːkɪtekt/", meaning: "n. 建筑师" },
        { word: "architecture", phonetic: "/ˈɑːkɪtektʃə(r)/", meaning: "n. 建筑学，建筑式样" },
        { word: "area", phonetic: "/ˈeəriə/", meaning: "n. 面积，地区，领域" },
        { word: "argue", phonetic: "/ˈɑːɡjuː/", meaning: "vi. 争论，辩论 vt. 辩论" },
        { word: "argument", phonetic: "/ˈɑːɡjumənt/", meaning: "n. 争论，辩论，理由" },
        { word: "arise", phonetic: "/əˈraɪz/", meaning: "vi. 出现，由…引起" },
        { word: "arithmetic", phonetic: "/əˈrɪθmətɪk/", meaning: "n. 算术，四则运算" },
        { word: "arm", phonetic: "/ɑːm/", meaning: "n. 手臂，武器 vt. 武装" },
        { word: "army", phonetic: "/ˈɑːmi/", meaning: "n. 军队，陆军" },
        { word: "around", phonetic: "/əˈraʊnd/", meaning: "prep. 在…周围" },
        { word: "arrange", phonetic: "/əˈreɪndʒ/", meaning: "vt. 整理，排列，安排" },
        { word: "arrangement", phonetic: "/əˈreɪndʒmənt/", meaning: "n. 整理，排列，安排" },
        { word: "arrest", phonetic: "/əˈrest/", meaning: "vt. 逮捕，拘留 n. 逮捕" },
        { word: "arrival", phonetic: "/əˈraɪvl/", meaning: "n. 到达，到达者" },
        { word: "arrive", phonetic: "/əˈraɪv/", meaning: "vi. 到达，来临，达到" },
        { word: "arrow", phonetic: "/ˈærəʊ/", meaning: "n. 箭，箭状物，箭头" },
        { word: "art", phonetic: "/ɑːt/", meaning: "n. 艺术，美术，技艺" },
        { word: "article", phonetic: "/ˈɑːtɪkl/", meaning: "n. 文章，条款，物品" },
        { word: "artificial", phonetic: "/ˌɑːtɪˈfɪʃl/", meaning: "a. 人工的，人造的" },
        { word: "artist", phonetic: "/ˈɑːtɪst/", meaning: "n. 艺术家，美术家" },
        { word: "artistic", phonetic: "/ɑːˈtɪstɪk/", meaning: "a. 艺术的，艺术家的" },
        { word: "as", phonetic: "/æz/", meaning: "conj. 当…时候，因为" },
        { word: "ash", phonetic: "/æʃ/", meaning: "n. 灰，灰末，骨灰" },
        { word: "ashamed", phonetic: "/əˈʃeɪmd/", meaning: "a. 惭愧的，羞耻的" },
        { word: "Asia", phonetic: "/ˈeɪʒə/", meaning: "n. 亚洲" },
        { word: "Asian", phonetic: "/ˈeɪʒən/", meaning: "a. 亚洲的 n. 亚洲人" },
        { word: "aside", phonetic: "/əˈsaɪd/", meaning: "ad. 在旁边，到旁边" },
        { word: "ask", phonetic: "/ɑːsk/", meaning: "v. 问，要求，邀请" },
        { word: "asleep", phonetic: "/əˈsliːp/", meaning: "a. 睡着的，睡熟的" },
        { word: "aspect", phonetic: "/ˈæspekt/", meaning: "n. 方面，样子，外表" },
        { word: "aspiration", phonetic: "/ˌæspəˈreɪʃn/", meaning: "n. 强烈的愿望，志向" },
        { word: "assassinate", phonetic: "/əˈsæsɪneɪt/", meaning: "vt. 暗杀，行刺" },
        { word: "assault", phonetic: "/əˈsɔːlt/", meaning: "vt. 袭击，殴打 n. 攻击" },
        { word: "assemble", phonetic: "/əˈsembl/", meaning: "vt. 集合，装配，收集" },
        { word: "assembly", phonetic: "/əˈsembli/", meaning: "n. 集合，集会，装配" },
        { word: "assert", phonetic: "/əˈsɜːt/", meaning: "vt. 断言，宣称，维护" },
        { word: "assign", phonetic: "/əˈsaɪn/", meaning: "vt. 指派，分配，指定" },
        { word: "assignment", phonetic: "/əˈsaɪnmənt/", meaning: "n. 任务，指定的作业" },
        { word: "assist", phonetic: "/əˈsɪst/", meaning: "vt. 援助，帮助" },
        { word: "assistance", phonetic: "/əˈsɪstəns/", meaning: "n. 协助，援助" },
        { word: "assistant", phonetic: "/əˈsɪstənt/", meaning: "n. 助手，助理，助教" },
        { word: "associate", phonetic: "/əˈsəʊsieɪt/", meaning: "v. 联想，交往 n. 伙伴" },
        { word: "association", phonetic: "/əˌsəʊsiˈeɪʃn/", meaning: "n. 协会，团体，联合" },
        { word: "assume", phonetic: "/əˈsjuːm/", meaning: "vt. 假定，承担，呈现" },
        { word: "assumption", phonetic: "/əˈsʌmpʃn/", meaning: "n. 假定，设想，担任" },
        { word: "assure", phonetic: "/əˈʃʊə(r)/", meaning: "vt. 使确信，向…保证" },
        { word: "astonish", phonetic: "/əˈstɒnɪʃ/", meaning: "vt. 使惊讶，使吃惊" },
        { word: "astronaut", phonetic: "/ˈæstrənɔːt/", meaning: "n. 宇宙航行员" },
        { word: "astronomy", phonetic: "/əˈstrɒnəmi/", meaning: "n. 天文学" },
        { word: "asylum", phonetic: "/əˈsaɪləm/", meaning: "n. 避难所，庇护" },
        { word: "asynchronous", phonetic: "/eɪˈsɪŋkrənəs/", meaning: "a. 异步的，不同时的" },
        { word: "at", phonetic: "/æt/", meaning: "prep. 在…，向…，对…" },
        { word: "athlete", phonetic: "/ˈæθliːt/", meaning: "n. 运动员" },
        { word: "athletic", phonetic: "/æθˈletɪk/", meaning: "a. 运动的，体育的" },
        { word: "atmosphere", phonetic: "/ˈætməsfɪə(r)/", meaning: "n. 大气，气氛" },
        { word: "atom", phonetic: "/ˈætəm/", meaning: "n. 原子，微粒" },
        { word: "atomic", phonetic: "/əˈtɒmɪk/", meaning: "a. 原子的，原子能的" },
        { word: "attach", phonetic: "/əˈtætʃ/", meaning: "vt. 缚，系，贴，附加" },
        { word: "attack", phonetic: "/əˈtæk/", meaning: "v. 攻击，进攻 n. 攻击" },
        { word: "attempt", phonetic: "/əˈtempt/", meaning: "vt. 尝试，试图 n. 尝试" },
        { word: "attend", phonetic: "/əˈtend/", meaning: "vt. 出席，照顾，护理" },
        { word: "attention", phonetic: "/əˈtenʃn/", meaning: "n. 注意，注意力，留心" },
        { word: "attentive", phonetic: "/əˈtentɪv/", meaning: "a. 注意的，留神的" },
        { word: "attitude", phonetic: "/ˈætɪtjuːd/", meaning: "n. 态度，看法，姿势" },
        { word: "attorney", phonetic: "/əˈtɜːni/", meaning: "n. 律师，代理人" },
        { word: "attract", phonetic: "/əˈtrækt/", meaning: "vt. 吸引，引起，诱惑" },
        { word: "attraction", phonetic: "/əˈtrækʃn/", meaning: "n. 吸引，吸引力，引力" },
        { word: "attractive", phonetic: "/əˈtræktɪv/", meaning: "a. 有吸引力的" },
        { word: "attribute", phonetic: "/əˈtrɪbjuːt/", meaning: "vt. 把…归因于 n. 属性" },
        { word: "auction", phonetic: "/ˈɔːkʃn/", meaning: "n. 拍卖" },
        { word: "audience", phonetic: "/ˈɔːdiəns/", meaning: "n. 听众，观众，读者" },
        { word: "audio", phonetic: "/ˈɔːdiəʊ/", meaning: "a. 音频的，声音的" },
        { word: "audit", phonetic: "/ˈɔːdɪt/", meaning: "v. 审计，查账" },
        { word: "auditorium", phonetic: "/ˌɔːdɪˈtɔːriəm/", meaning: "n. 听众席，观众席" },
        { word: "August", phonetic: "/ˈɔːɡəst/", meaning: "n. 八月" },
        { word: "aunt", phonetic: "/ɑːnt/", meaning: "n. 伯母，婶母，姑母" },
        { word: "Australia", phonetic: "/ɒˈstreɪliə/", meaning: "n. 澳大利亚" },
        { word: "Australian", phonetic: "/ɒˈstreɪliən/", meaning: "a. 澳大利亚的 n. 澳大利亚人" },
        { word: "author", phonetic: "/ˈɔːθə(r)/", meaning: "n. 作者，作家" },
        { word: "authority", phonetic: "/ɔːˈθɒrəti/", meaning: "n. 权力，权威，当局" },
        { word: "auto", phonetic: "/ˈɔːtəʊ/", meaning: "n. 汽车" },
        { word: "automatic", phonetic: "/ˌɔːtəˈmætɪk/", meaning: "a. 自动的，机械的" },
        { word: "automation", phonetic: "/ˌɔːtəˈmeɪʃn/", meaning: "n. 自动，自动化" },
        { word: "automobile", phonetic: "/ˈɔːtəməbiːl/", meaning: "n. 汽车" },
        { word: "autonomous", phonetic: "/ɔːˈtɒnəməs/", meaning: "a. 自治的，自主的" },
        { word: "autonomy", phonetic: "/ɔːˈtɒnəmi/", meaning: "n. 自治，自主" },
        { word: "autumn", phonetic: "/ˈɔːtəm/", meaning: "n. 秋，秋季" },
        { word: "available", phonetic: "/əˈveɪləbl/", meaning: "a. 可利用的，可得到的" },
        { word: "avenue", phonetic: "/ˈævənjuː/", meaning: "n. 林荫道，大街" },
        { word: "average", phonetic: "/ˈævərɪdʒ/", meaning: "n. 平均数，平均" },
        { word: "avert", phonetic: "/əˈvɜːt/", meaning: "vt. 防止，避免，转移" },
        { word: "aviation", phonetic: "/ˌeɪviˈeɪʃn/", meaning: "n. 航空，航空学" },
        { word: "avoid", phonetic: "/əˈvɔɪd/", meaning: "vt. 避免，躲开，撤消" },
        { word: "await", phonetic: "/əˈweɪt/", meaning: "vt. 等候，期待" },
        { word: "awake", phonetic: "/əˈweɪk/", meaning: "a. 醒着的 vt. 唤醒" },
        { word: "award", phonetic: "/əˈwɔːd/", meaning: "n. 奖，奖品，判定" },
        { word: "aware", phonetic: "/əˈweə(r)/", meaning: "a. 知道的，意识到的" },
        { word: "awful", phonetic: "/ˈɔːfl/", meaning: "a. 令人不愉快的" },
        { word: "awkward", phonetic: "/ˈɔːkwəd/", meaning: "a. 笨拙的，尴尬的" },
        { word: "ax", phonetic: "/æks/", meaning: "n. 斧子" },
        { word: "axis", phonetic: "/ˈæksɪs/", meaning: "n. 轴，轴线，中心线" },
        { word: "baby", phonetic: "/ˈbeɪbi/", meaning: "n. 婴儿" },
        { word: "back", phonetic: "/bæk/", meaning: "ad. 向后，回原处，回" },
        { word: "background", phonetic: "/ˈbækɡraʊnd/", meaning: "n. 背景，后景，经历" },
        { word: "backward", phonetic: "/ˈbækwəd/", meaning: "a. 向后的，倒的 ad. 倒" },
        { word: "bacon", phonetic: "/ˈbeɪkən/", meaning: "n. 咸猪肉，熏猪肉" },
        { word: "bacteria", phonetic: "/bækˈtɪəriə/", meaning: "n. 细菌" },
        { word: "bad", phonetic: "/bæd/", meaning: "a. 坏的，恶的，严重的" },
        { word: "badly", phonetic: "/ˈbædli/", meaning: "ad. 坏，差，严重地" },
        { word: "badminton", phonetic: "/ˈbædmɪntən/", meaning: "n. 羽毛球" },
        { word: "bag", phonetic: "/bæɡ/", meaning: "n. 袋，包，钱包，背包" },
        { word: "baggage", phonetic: "/ˈbæɡɪdʒ/", meaning: "n. 行李" },
        { word: "bake", phonetic: "/beɪk/", meaning: "vt. 烤，烘，焙，烧硬" },
        { word: "balance", phonetic: "/ˈbæləns/", meaning: "n. 平衡，均衡，余额" },
        { word: "ball", phonetic: "/bɔːl/", meaning: "n. 球，球状物，舞会" },
        { word: "balloon", phonetic: "/bəˈluːn/", meaning: "n. 气球" },
        { word: "ban", phonetic: "/bæn/", meaning: "vt. 禁止，取缔 n. 禁止" },
        { word: "banana", phonetic: "/bəˈnɑːnə/", meaning: "n. 香蕉" },
        { word: "band", phonetic: "/bænd/", meaning: "n. 乐队，带，波段" },
        { word: "bank", phonetic: "/bæŋk/", meaning: "n. 银行，库，堤" },
        { word: "bar", phonetic: "/bɑː(r)/", meaning: "n. 酒吧间，条，杆" },
        { word: "barbecue", phonetic: "/ˈbɑːbɪkjuː/", meaning: "n. 烤肉，烤肉架" },
        { word: "bargain", phonetic: "/ˈbɑːɡən/", meaning: "n. 交易，便宜货 v. 讨价还价" },
        { word: "barrier", phonetic: "/ˈbæriə(r)/", meaning: "n. 栅栏，屏障，障碍" },
        { word: "base", phonetic: "/beɪs/", meaning: "n. 基础，底层，基地" },
        { word: "basic", phonetic: "/ˈbeɪsɪk/", meaning: "a. 基本的，基础的" },
        { word: "basically", phonetic: "/ˈbeɪsɪkli/", meaning: "ad. 基本上" },
        { word: "basin", phonetic: "/ˈbeɪsn/", meaning: "n. 盆，洗脸盆，盆地" },
        { word: "basis", phonetic: "/ˈbeɪsɪs/", meaning: "n. 基础，根据" },
        { word: "basket", phonetic: "/ˈbɑːskɪt/", meaning: "n. 篮，篓，筐" },
        { word: "basketball", phonetic: "/ˈbɑːskɪtbɔːl/", meaning: "n. 篮球" },
        { word: "bat", phonetic: "/bæt/", meaning: "n. 球拍，球棒，蝙蝠" },
        { word: "batch", phonetic: "/bætʃ/", meaning: "n. 一批，一组，一群" },
        { word: "bath", phonetic: "/bɑːθ/", meaning: "n. 浴，洗澡，浴缸" },
        { word: "bathe", phonetic: "/beɪð/", meaning: "vt. 给…洗澡 vi. 洗澡" },
        { word: "bathroom", phonetic: "/ˈbɑːθruːm/", meaning: "n. 浴室，盥洗室" },
        { word: "battery", phonetic: "/ˈbætri/", meaning: "n. 电池，蓄电池" },
        { word: "battle", phonetic: "/ˈbætl/", meaning: "n. 战役，斗争 vi. 作战" },
        { word: "be", phonetic: "/biː/", meaning: "v. 是，在，做" },
        { word: "beach", phonetic: "/biːtʃ/", meaning: "n. 海滩，湖滩，河滩" },
        { word: "beam", phonetic: "/biːm/", meaning: "n. 梁，横梁，束，柱" },
        { word: "bean", phonetic: "/biːn/", meaning: "n. 豆，蚕豆" },
        { word: "bear", phonetic: "/beə(r)/", meaning: "vt. 容忍，负担，生育" },
        { word: "beast", phonetic: "/biːst/", meaning: "n. 兽，野兽，牲畜" },
        { word: "beat", phonetic: "/biːt/", meaning: "vt. 打，敲，打败" },
        { word: "beautiful", phonetic: "/ˈbjuːtɪfl/", meaning: "a. 美的，美丽的" },
        { word: "beauty", phonetic: "/ˈbjuːti/", meaning: "n. 美，美丽，美人" },
        { word: "because", phonetic: "/bɪˈkəz/", meaning: "conj. 因为" },
        { word: "become", phonetic: "/bɪˈkʌm/", meaning: "vi. 变成，成为，变得" },
        { word: "bed", phonetic: "/bed/", meaning: "n. 床，床位，河床" },
        { word: "bedroom", phonetic: "/ˈbedruːm/", meaning: "n. 卧室" },
        { word: "bee", phonetic: "/biː/", meaning: "n. 蜜蜂" },
        { word: "beef", phonetic: "/biːf/", meaning: "n. 牛肉" },
        { word: "beer", phonetic: "/bɪə(r)/", meaning: "n. 啤酒" },
        { word: "before", phonetic: "/bɪˈfɔː(r)/", meaning: "prep. 在…以前，在…前面" },
        { word: "beforehand", phonetic: "/bɪˈfɔːhænd/", meaning: "ad. 预先，事先" },
        { word: "begin", phonetic: "/bɪˈɡɪn/", meaning: "v. 开始，着手" },
        { word: "beginner", phonetic: "/bɪˈɡɪnə(r)/", meaning: "n. 初学者，生手" },
        { word: "beginning", phonetic: "/bɪˈɡɪnɪŋ/", meaning: "n. 开始，开端，起源" },
        { word: "behalf", phonetic: "/bɪˈhɑːf/", meaning: "n. 利益，维护，支持" },
        { word: "behave", phonetic: "/bɪˈheɪv/", meaning: "vi. 表现，举止，运转" },
        { word: "behavior", phonetic: "/bɪˈheɪvjə(r)/", meaning: "n. 行为，举止，态度" },
        { word: "behind", phonetic: "/bɪˈhaɪnd/", meaning: "prep. 在…后面，落后于" },
        { word: "being", phonetic: "/ˈbiːɪŋ/", meaning: "n. 存在，生物，生命" },
        { word: "belief", phonetic: "/bɪˈliːf/", meaning: "n. 相信，信念，信仰" },
        { word: "believe", phonetic: "/bɪˈliːv/", meaning: "vt. 相信，认为" },
        { word: "bell", phonetic: "/bel/", meaning: "n. 钟，铃，门铃" },
        { word: "belong", phonetic: "/bɪˈlɒŋ/", meaning: "vi. 属于，应归入" },
        { word: "beloved", phonetic: "/bɪˈlʌvd/", meaning: "a. 为…所爱的 n. 爱人" },
        { word: "below", phonetic: "/bɪˈləʊ/", meaning: "prep. 在…下面，低于" },
        { word: "belt", phonetic: "/belt/", meaning: "n. 带，腰带，地带" },
        { word: "bench", phonetic: "/bentʃ/", meaning: "n. 长凳，条凳，工作台" },
        { word: "bend", phonetic: "/bend/", meaning: "vt. 使弯曲 vi. 弯曲" },
        { word: "beneath", phonetic: "/bɪˈniːθ/", meaning: "prep. 在…下方" },
        { word: "beneficial", phonetic: "/ˌbenɪˈfɪʃl/", meaning: "a. 有利的，有益的" },
        { word: "benefit", phonetic: "/ˈbenɪfɪt/", meaning: "n. 利益，恩惠，津贴" },
        { word: "bent", phonetic: "/bent/", meaning: "a. 弯的，决心的" },
        { word: "beside", phonetic: "/bɪˈsaɪd/", meaning: "prep. 在…旁边，和…比较" },
        { word: "besides", phonetic: "/bɪˈsaɪdz/", meaning: "ad. 而且，此外 prep. 除…之外" },
        { word: "best", phonetic: "/best/", meaning: "a. 最好的 ad. 最好地" },
        { word: "bet", phonetic: "/bet/", meaning: "v. 赌，打赌 n. 打赌" },
        { word: "betray", phonetic: "/bɪˈtreɪ/", meaning: "vt. 背叛，暴露，泄露" },
        { word: "better", phonetic: "/ˈbetə(r)/", meaning: "a. 较好的 ad. 更好地" },
        { word: "between", phonetic: "/bɪˈtwiːn/", meaning: "prep. 在…之间，在…中间" },
        { word: "beyond", phonetic: "/bɪˈjɒnd/", meaning: "prep. 超出，在…那边" },
        { word: "bicycle", phonetic: "/ˈbaɪsɪkl/", meaning: "n. 自行车" },
        { word: "bid", phonetic: "/bɪd/", meaning: "vt. 命令，出价 n. 出价" },
        { word: "big", phonetic: "/bɪɡ/", meaning: "a. 大的，重要的" },
        { word: "bike", phonetic: "/baɪk/", meaning: "n. 自行车" },
        { word: "bill", phonetic: "/bɪl/", meaning: "n. 账单，招贴，票据" },
        { word: "billion", phonetic: "/ˈbɪljən/", meaning: "num. 十亿，千兆" },
        { word: "bin", phonetic: "/bɪn/", meaning: "n. 箱柜" },
        { word: "binary", phonetic: "/ˈbaɪnəri/", meaning: "a. 二进位的，二元的" },
        { word: "bind", phonetic: "/baɪnd/", meaning: "vt. 捆绑，包扎，装钉" },
        { word: "biography", phonetic: "/baɪˈɒɡrəfi/", meaning: "n. 传记" },
        { word: "biology", phonetic: "/baɪˈɒlədʒi/", meaning: "n. 生物学，生态学" },
        { word: "bird", phonetic: "/bɜːd/", meaning: "n. 鸟，禽" },
        { word: "birth", phonetic: "/bɜːθ/", meaning: "n. 出生，分娩，出身" },
        { word: "birthday", phonetic: "/ˈbɜːθdeɪ/", meaning: "n. 生日" },
        { word: "biscuit", phonetic: "/ˈbɪskɪt/", meaning: "n. 饼干，点心" },
        { word: "bit", phonetic: "/bɪt/", meaning: "n. 一点，一些，小片" },
        { word: "bite", phonetic: "/baɪt/", meaning: "vt. 咬，叮，螫 n. 咬" },
        { word: "bitter", phonetic: "/ˈbɪtə(r)/", meaning: "a. 痛苦的，严寒的" },
        { word: "bizarre", phonetic: "/bɪˈzɑː(r)/", meaning: "a. 奇异的，古怪的" },
        { word: "black", phonetic: "/blæk/", meaning: "a. 黑色的，黑暗的" },
        { word: "blackboard", phonetic: "/ˈblækbɔːd/", meaning: "n. 黑板" },
        { word: "blade", phonetic: "/bleɪd/", meaning: "n. 刀刃，刀片，叶片" },
        { word: "blame", phonetic: "/bleɪm/", meaning: "vt. 责备，把…归咎于" },
        { word: "blank", phonetic: "/blæŋk/", meaning: "a. 空白的 n. 空白" },
        { word: "blanket", phonetic: "/ˈblæŋkɪt/", meaning: "n. 毯子" },
        { word: "blast", phonetic: "/blɑːst/", meaning: "n. 爆炸，冲击波 vt. 炸" },
        { word: "bleed", phonetic: "/bliːd/", meaning: "vi. 出血，流血" },
        { word: "blend", phonetic: "/blend/", meaning: "v. 混合 n. 混合物" },
        { word: "blind", phonetic: "/blaɪnd/", meaning: "a. 瞎的，盲目的" },
        { word: "block", phonetic: "/blɒk/", meaning: "n. 街区，木块，石块" },
        { word: "blond", phonetic: "/blɒnd/", meaning: "a. 白肤金发的 n. 白肤金发的人" },
        { word: "blood", phonetic: "/blʌd/", meaning: "n. 血，血液，血统" },
        { word: "blow", phonetic: "/bləʊ/", meaning: "v. 吹，吹动，吹响" },
        { word: "blue", phonetic: "/bluː/", meaning: "a. 蓝色的 n. 蓝色" },
        { word: "blunder", phonetic: "/ˈblʌndə(r)/", meaning: "n. 错误，大错" },
        { word: "blunt", phonetic: "/blʌnt/", meaning: "a. 钝的，生硬的" },
        { word: "blush", phonetic: "/blʌʃ/", meaning: "vi. 脸红，害臊 n. 脸红" },
        { word: "board", phonetic: "/bɔːd/", meaning: "n. 板，木板，纸板" },
        { word: "boat", phonetic: "/bəʊt/", meaning: "n. 船，小船" },
        { word: "body", phonetic: "/ˈbɒdi/", meaning: "n. 身体，主体，尸体" },
        { word: "boil", phonetic: "/bɔɪl/", meaning: "vi. 沸腾，汽化 vt. 煮沸" },
        { word: "bold", phonetic: "/bəʊld/", meaning: "a. 大胆的，冒失的" },
        { word: "bolt", phonetic: "/bəʊlt/", meaning: "n. 螺栓，插销 vt. 闩门" },
        { word: "bomb", phonetic: "/bɒm/", meaning: "n. 炸弹 vt. 轰炸" },
        { word: "bond", phonetic: "/bɒnd/", meaning: "n. 联结，联系，公债" },
        { word: "bone", phonetic: "/bəʊn/", meaning: "n. 骨，骨骼" },
        { word: "bonus", phonetic: "/ˈbəʊnəs/", meaning: "n. 奖金，额外津贴" },
        { word: "book", phonetic: "/bʊk/", meaning: "n. 书，书籍 vt. 预定" },
        { word: "boot", phonetic: "/buːt/", meaning: "n. 靴子，长统靴" },
        { word: "border", phonetic: "/ˈbɔːdə(r)/", meaning: "n. 边，边缘，边界" },
        { word: "bore", phonetic: "/bɔː(r)/", meaning: "vt. 使厌烦，钻孔" },
        { word: "born", phonetic: "/bɔːn/", meaning: "a. 天生的，生来的" },
        { word: "borrow", phonetic: "/ˈbɒrəʊ/", meaning: "vt. 借，借用，借用" },
        { word: "boss", phonetic: "/bɒs/", meaning: "n. 老板，上司 vt. 指挥" },
        { word: "botanical", phonetic: "/bəˈtænɪkl/", meaning: "a. 植物学的" },
        { word: "botany", phonetic: "/ˈbɒtəni/", meaning: "n. 植物学" },
        { word: "both", phonetic: "/bəʊθ/", meaning: "pron. 两者(都)" },
        { word: "bottle", phonetic: "/ˈbɒtl/", meaning: "n. 瓶，酒瓶，一瓶" },
        { word: "bottom", phonetic: "/ˈbɒtəm/", meaning: "n. 底，底部，根基" },
        { word: "bounce", phonetic: "/baʊns/", meaning: "vi. 反跳，弹起，弹跳" },
        { word: "bound", phonetic: "/baʊnd/", meaning: "a. 一定的，必然的" },
        { word: "boundary", phonetic: "/ˈbaʊndri/", meaning: "n. 分界线，边界" },
        { word: "bow", phonetic: "/baʊ/", meaning: "n. 弓，蝴蝶结，鞠躬" },
        { word: "bowl", phonetic: "/bəʊl/", meaning: "n. 碗，钵，碗状物" },
        { word: "box", phonetic: "/bɒks/", meaning: "n. 箱，盒，包箱" },
        { word: "boxing", phonetic: "/ˈbɒksɪŋ/", meaning: "n. 拳击，拳术" },
        { word: "boy", phonetic: "/bɔɪ/", meaning: "n. 男孩，少年，家伙" },
        { word: "brain", phonetic: "/breɪn/", meaning: "n. 脑，脑力，智能" },
        { word: "branch", phonetic: "/brɑːntʃ/", meaning: "n. 枝条，分支，部门" },
        { word: "brand", phonetic: "/brænd/", meaning: "n. 商品，烙印 vt. 铭刻" },
        { word: "brass", phonetic: "/brɑːs/", meaning: "n. 黄铜，黄铜器" },
        { word: "brave", phonetic: "/breɪv/", meaning: "a. 勇敢的，华丽的" },
        { word: "bread", phonetic: "/bred/", meaning: "n. 面包" },
        { word: "break", phonetic: "/breɪk/", meaning: "vt. 打破，损坏，破坏" },
        { word: "breakfast", phonetic: "/ˈbrekfəst/", meaning: "n. 早饭，早餐" },
        { word: "breath", phonetic: "/breθ/", meaning: "n. 气息，呼吸，气味" },
        { word: "breathe", phonetic: "/briːð/", meaning: "vi. 呼吸 vt. 呼吸" },
        { word: "breed", phonetic: "/briːd/", meaning: "n. 品种 vt. 使繁殖" },
        { word: "breeze", phonetic: "/briːz/", meaning: "n. 微风，和风" },
        { word: "brick", phonetic: "/brɪk/", meaning: "n. 砖，砖块，砖状物" },
        { word: "bride", phonetic: "/braɪd/", meaning: "n. 新娘" },
        { word: "bridge", phonetic: "/brɪdʒ/", meaning: "n. 桥，桥梁，桥牌" },
        { word: "brief", phonetic: "/briːf/", meaning: "a. 简短的，短暂的" },
        { word: "bright", phonetic: "/braɪt/", meaning: "a. 明亮的，聪明的" },
        { word: "brilliant", phonetic: "/ˈbrɪliənt/", meaning: "a. 光辉的，卓越的" },
        { word: "bring", phonetic: "/brɪŋ/", meaning: "vt. 带来，引起，促使" },
        { word: "brisk", phonetic: "/brɪsk/", meaning: "a. 活泼的，敏捷的" },
        { word: "brochure", phonetic: "/ˈbrəʊʃə(r)/", meaning: "n. 小册子，说明书" },
        { word: "broken", phonetic: "/ˈbrəʊkən/", meaning: "a. 被打碎的，骨折的" },
        { word: "bronze", phonetic: "/brɒnz/", meaning: "n. 青铜，青铜制品" },
        { word: "brood", phonetic: "/bruːd/", meaning: "n. 同窝幼鸟 vt. 孵" },
        { word: "brook", phonetic: "/brʊk/", meaning: "n. 小河，溪流" },
        { word: "broom", phonetic: "/bruːm/", meaning: "n. 扫帚" },
        { word: "brother", phonetic: "/ˈbrʌðə(r)/", meaning: "n. 兄弟" },
        { word: "brow", phonetic: "/braʊ/", meaning: "n. 额，眉毛，眼眉" },
        { word: "brown", phonetic: "/braʊn/", meaning: "a. 褐色的，棕色的" },
        { word: "brush", phonetic: "/brʌʃ/", meaning: "n. 刷子，画笔 vt. 刷" },
        { word: "bucket", phonetic: "/ˈbʌkɪt/", meaning: "n. 水桶，吊桶" },
        { word: "budget", phonetic: "/ˈbʌdʒɪt/", meaning: "n. 预算，预算案" },
        { word: "buffalo", phonetic: "/ˈbʌfələʊ/", meaning: "n. 水牛，美洲野牛" },
        { word: "build", phonetic: "/bɪld/", meaning: "vt. 建筑，建造，建立" },
        { word: "building", phonetic: "/ˈbɪldɪŋ/", meaning: "n. 建筑物，大楼" },
        { word: "bulb", phonetic: "/bʌlb/", meaning: "n. 电灯泡，球状物" },
        { word: "bulk", phonetic: "/bʌlk/", meaning: "n. 物体，容积，大批" },
        { word: "bullet", phonetic: "/ˈbʌlɪt/", meaning: "n. 枪弹，子弹，弹丸" },
        { word: "bundle", phonetic: "/ˈbʌndl/", meaning: "n. 捆，包，束，卷" },
        { word: "bureau", phonetic: "/ˈbjʊərəʊ/", meaning: "n. 局，司，处，社，所" },
        { word: "burn", phonetic: "/bɜːn/", meaning: "v. 燃烧，烧伤 n. 烧伤" },
        { word: "burst", phonetic: "/bɜːst/", meaning: "v. 爆炸，破裂 n. 爆炸" },
        { word: "bury", phonetic: "/ˈberi/", meaning: "vt. 埋葬，埋藏，掩藏" },
        { word: "bus", phonetic: "/bʌs/", meaning: "n. 公共汽车" },
        { word: "bush", phonetic: "/bʊʃ/", meaning: "n. 灌木，灌木丛，矮树" },
        { word: "business", phonetic: "/ˈbɪznəs/", meaning: "n. 商业，生意，事务" },
        { word: "busy", phonetic: "/ˈbɪzi/", meaning: "a. 忙的，繁忙的" },
        { word: "but", phonetic: "/bʌt/", meaning: "conj. 但是，可是" },
        { word: "butcher", phonetic: "/ˈbʊtʃə(r)/", meaning: "n. 屠夫，屠户" },
        { word: "butter", phonetic: "/ˈbʌtə(r)/", meaning: "n. 黄油，奶油" },
        { word: "button", phonetic: "/ˈbʌtn/", meaning: "n. 扣子，按钮 vt. 扣紧" },
        { word: "buy", phonetic: "/baɪ/", meaning: "vt. 买，购买" },
        { word: "by", phonetic: "/baɪ/", meaning: "prep. 在…旁，被，由" }
    ],
    
    // 大学英语六级词汇
    cet6: [
        { word: "abbreviate", phonetic: "/əˈbriːvieɪt/", meaning: "vt. 缩写，使简短" },
        { word: "abdomen", phonetic: "/ˈæbdəmən/", meaning: "n. 腹，腹部" },
        { word: "abide", phonetic: "/əˈbaɪd/", meaning: "vi. 遵守，坚持" },
        { word: "abound", phonetic: "/əˈbaʊnd/", meaning: "vi. 多，大量存在" },
        { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "ad. (在)国外，到处" },
        { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "a. 突然的，意外的" },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "a. 绝对的，完全的" },
        { word: "absorb", phonetic: "/əbˈsɔːb/", meaning: "vt. 吸收，使专心" },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "a. 抽象的 n. 摘要" },
        { word: "absurd", phonetic: "/əbˈsɜːd/", meaning: "a. 不合理的，荒唐的" },
        { word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "a. 丰富的，充分的" },
        { word: "abuse", phonetic: "/əˈbjuːs/", meaning: "vt. 滥用，虐待 n. 滥用" },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "a. 学术的，教学的" },
        { word: "academy", phonetic: "/əˈkædəmi/", meaning: "n. 学院，研究院" },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "vt. 加速，促进" },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 接近，通道，入口" },
        { word: "accessible", phonetic: "/əkˈsesəbl/", meaning: "a. 易接近的，可得到的" },
        { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", meaning: "vt. 容纳，供应，适应" },
        { word: "accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "n. 住处，膳宿" },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "vt. 陪伴，陪同，伴随" },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "vt. 达到(目的)，完成" },
        { word: "accord", phonetic: "/əˈkɔːd/", meaning: "n. 一致，符合，调和" },
        { word: "accordingly", phonetic: "/əˈkɔːdɪŋli/", meaning: "ad. 因此，依照" },
        { word: "accountant", phonetic: "/əˈkaʊntənt/", meaning: "n. 会计，出纳" },
        { word: "accumulate", phonetic: "/əˈkjuːmjuleɪt/", meaning: "vt. 积累 vi. 堆积" },
        { word: "accuracy", phonetic: "/ˈækjərəsi/", meaning: "n. 准确(性)，精确" },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "a. 准确的，正确无误的" },
        { word: "accuse", phonetic: "/əˈkjuːz/", meaning: "vt. 指责，归咎于" },
        { word: "accustomed", phonetic: "/əˈkʌstəmd/", meaning: "a. 惯常的，习惯的" },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "vt. 完成，达到，获得" }
    ],
    
    // 雅思词汇
    ielts: [
        { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃，遗弃，抛弃" },
        { word: "ability", phonetic: "/əˈbɪləti/", meaning: "n. 能力，才能" },
        { word: "abnormal", phonetic: "/æbˈnɔːml/", meaning: "adj. 反常的，异常的" },
        { word: "abolish", phonetic: "/əˈbɒlɪʃ/", meaning: "v. 废除，废止" },
        { word: "abortion", phonetic: "/əˈbɔːʃn/", meaning: "n. 流产，堕胎" },
        { word: "abound", phonetic: "/əˈbaʊnd/", meaning: "v. 大量存在，充满" },
        { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "adv. 在国外，到国外" },
        { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "adj. 突然的，意外的" },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "adj. 绝对的，完全的" },
        { word: "absorb", phonetic: "/əbˈsɔːb/", meaning: "v. 吸收，吸引…的注意" },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的 n. 摘要" },
        { word: "abuse", phonetic: "/əˈbjuːs/", meaning: "v. 滥用，虐待 n. 滥用" },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的，教学的" },
        { word: "academy", phonetic: "/əˈkædəmi/", meaning: "n. 学院，研究院" },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速，促进" },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 接近，通道，入口" },
        { word: "accessible", phonetic: "/əkˈsesəbl/", meaning: "adj. 易接近的，可得到的" },
        { word: "accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "n. 住处，膳宿" },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "v. 陪伴，陪同，伴随" },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "v. 完成，实现，达到" },
        { word: "account", phonetic: "/əˈkaʊnt/", meaning: "n. 账户，账目，描述" },
        { word: "accountant", phonetic: "/əˈkaʊntənt/", meaning: "n. 会计，出纳" },
        { word: "accumulate", phonetic: "/əˈkjuːmjuleɪt/", meaning: "v. 积累，堆积" },
        { word: "accuracy", phonetic: "/ˈækjərəsi/", meaning: "n. 准确性，精确性" },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "adj. 准确的，精确的" },
        { word: "accuse", phonetic: "/əˈkjuːz/", meaning: "v. 指责，控告" },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "v. 完成，达到，获得" },
        { word: "achievement", phonetic: "/əˈtʃiːvmənt/", meaning: "n. 成就，完成，达到" },
        { word: "acid", phonetic: "/ˈæsɪd/", meaning: "adj. 酸的，酸性的" },
        { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "v. 承认，确认，答谢" }
    ],
    
    // 托福词汇
    toefl: [
        { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃，离弃，遗弃" },
        { word: "ability", phonetic: "/əˈbɪləti/", meaning: "n. 能力，才能" },
        { word: "abnormal", phonetic: "/æbˈnɔːml/", meaning: "adj. 不正常的，反常的" },
        { word: "abolish", phonetic: "/əˈbɒlɪʃ/", meaning: "v. 废除，废止" },
        { word: "abortion", phonetic: "/əˈbɔːʃn/", meaning: "n. 流产，堕胎" },
        { word: "abound", phonetic: "/əˈbaʊnd/", meaning: "v. 大量存在，充满" },
        { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "adv. 在国外，到国外" },
        { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "adj. 突然的，意外的" },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "adj. 绝对的，完全的" },
        { word: "absorb", phonetic: "/əbˈsɔːb/", meaning: "v. 吸收，吸引…的注意" },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的 n. 摘要" },
        { word: "abuse", phonetic: "/əˈbjuːs/", meaning: "v. 滥用，虐待 n. 滥用" },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的，教学的" },
        { word: "academy", phonetic: "/əˈkædəmi/", meaning: "n. 学院，研究院" },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速，促进" },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 接近，通道，入口" },
        { word: "accessible", phonetic: "/əkˈsesəbl/", meaning: "adj. 易接近的，可得到的" },
        { word: "accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "n. 住处，膳宿" },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "v. 陪伴，陪同，伴随" },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "v. 完成，实现，达到" },
        { word: "account", phonetic: "/əˈkaʊnt/", meaning: "n. 账户，账目，描述" },
        { word: "accountant", phonetic: "/əˈkaʊntənt/", meaning: "n. 会计，出纳" },
        { word: "accumulate", phonetic: "/əˈkjuːmjuleɪt/", meaning: "v. 积累，堆积" },
        { word: "accuracy", phonetic: "/ˈækjərəsi/", meaning: "n. 准确性，精确性" },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "adj. 准确的，精确的" },
        { word: "accuse", phonetic: "/əˈkjuːz/", meaning: "v. 指责，控告" },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "v. 完成，达到，获得" },
        { word: "achievement", phonetic: "/əˈtʃiːvmənt/", meaning: "n. 成就，完成，达到" },
        { word: "acid", phonetic: "/ˈæsɪd/", meaning: "adj. 酸的，酸性的" },
        { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "v. 承认，确认，答谢" }
    ],
    
    // 考研词汇
    kaoyan: [
        { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃，遗弃，抛弃" },
        { word: "ability", phonetic: "/əˈbɪləti/", meaning: "n. 能力，才能" },
        { word: "abnormal", phonetic: "/æbˈnɔːml/", meaning: "adj. 反常的，异常的" },
        { word: "abolish", phonetic: "/əˈbɒlɪʃ/", meaning: "v. 废除，废止" },
        { word: "abortion", phonetic: "/əˈbɔːʃn/", meaning: "n. 流产，堕胎" },
        { word: "abound", phonetic: "/əˈbaʊnd/", meaning: "v. 大量存在，充满" },
        { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "adv. 在国外，到国外" },
        { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "adj. 突然的，意外的" },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "adj. 绝对的，完全的" },
        { word: "absorb", phonetic: "/əbˈsɔːb/", meaning: "v. 吸收，吸引…的注意" },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的 n. 摘要" },
        { word: "abuse", phonetic: "/əˈbjuːs/", meaning: "v. 滥用，虐待 n. 滥用" },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的，教学的" },
        { word: "academy", phonetic: "/əˈkædəmi/", meaning: "n. 学院，研究院" },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速，促进" },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 接近，通道，入口" },
        { word: "accessible", phonetic: "/əkˈsesəbl/", meaning: "adj. 易接近的，可得到的" },
        { word: "accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "n. 住处，膳宿" },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "v. 陪伴，陪同，伴随" },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "v. 完成，实现，达到" },
        { word: "account", phonetic: "/əˈkaʊnt/", meaning: "n. 账户，账目，描述" },
        { word: "accountant", phonetic: "/əˈkaʊntənt/", meaning: "n. 会计，出纳" },
        { word: "accumulate", phonetic: "/əˈkjuːmjuleɪt/", meaning: "v. 积累，堆积" },
        { word: "accuracy", phonetic: "/ˈækjərəsi/", meaning: "n. 准确性，精确性" },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "adj. 准确的，精确的" },
        { word: "accuse", phonetic: "/əˈkjuːz/", meaning: "v. 指责，控告" },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "v. 完成，达到，获得" },
        { word: "achievement", phonetic: "/əˈtʃiːvmənt/", meaning: "n. 成就，完成，达到" },
        { word: "acid", phonetic: "/ˈæsɪd/", meaning: "adj. 酸的，酸性的" },
        { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "v. 承认，确认，答谢" }
    ]
};